version: '3'

services:
  nginx:
    hostname: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - web

  wordpress:
    hostname: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:80
      - 9000:9000
    environment:
      WORDPRESS_DB_NAME: mywordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_HOST: localhost
      WORDPRESS_URL: http://localhost:8080
      WORDPRESS_TITLE: "My WordPress Site"
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: password
      WORDPRESS_ADMIN_EMAIL: admin@example.com
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - web
  
  mariadb:
    hostname: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    # volumes:
    #   - mariadb:/var/lib/mysql
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  mariadb: 